---
title: "Ben Richmond"
subtitle: "Emissions Consultant and R/Data Science Enthusiast"
date-modified: now
date-format: "D MMMM, YYYY; HH:mm"
---

Hi! I'm Ben, and I work on the [UK's National Atmospheric Emissions Inventory (NAEI)](https://naei.beis.gov.uk). I'm the current Air Quality Lead, and work with the wider team to estimate emissions of over 60 pollutants from 1990 onwards.

In particular, I help calculate emissions of:

* Nitrogen Oxides (NO~X~)
* Particulate Matter < 2.5 μm (PM~2.5~)
* Ammonia (NH~3~)
* Non-Methane Volatile Organic Compounds (NMVOCs)
* Sulphur Dioxide (SO~2~)

In order to ascertain the UK's compliance against NECR Emission Reduction Commitments, in addition, I help to produce projections of emissions of the above pollutants through to 2040.

The NAEI also estimates the emissions of UK Greenhouse Gas emissions from 1990 onwards and reports these to the UNFCCC. GHGs include:
* Carbon Dioxide (CO~2~)
* Methane (CH~4~)
* Nitrous Oxide (N~2~O) 


Outside of working on the NAEI, my expertise also includes:

* Upgrading legacy systems from Excel/Access, and developing new systems into R/SQL 
* CLRTAP Lead Reviewer for the Stage 3 Review of Parties on behalf of [CEIP](https://www.ceip.at/status-of-reporting-and-review-results/2023-submission)
* Estimates of NMVOC emissions from the solvents sector
* Estimating annual emissions for the UK's Devolved Administrations




To learn more about Quarto websites visit <https://quarto.org/docs/websites>.
